from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
 
CPPPATH = [cwd]

group   = DefineGroup('mod_input', src, depend = ['RT_USING_INPUT_DEV'], CPPPATH = CPPPATH)

Return('group')
